services:
  whodb:
    image: nocodb/nocodb:0.257.2
    volumes:
      - ./volumes:/usr/app/data/ 
    ports:
      - "127.0.0.1:3366:8080"
    enviroment:
      NUXT_PUBLIC_NC_BACKEND_URL: https://db.nano-exp.com
